general {
    no_fade_in = false
    grace = 0
    disable_loading = true
}

background {
    monitor =
    path = screenshot # Isso captura a tela atual no momento do lock
    color = rgba(25, 20, 20, 1.0)
 
    # Ajuste o Blur aqui para ficar do seu gosto
    blur_passes = 3 # Quanto mais passes, mais "embaçado" (pesa um pouco mais na GPU)
    blur_size = 5   # Intensidade do desfoque
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0) # Borda invisível por padrão
    inner_color = rgba(255, 255, 255, 0.1) # Fundo semi-transparente
    font_color = rgb(200, 200, 200)
    fade_on_empty = false
    rounding = -1 # Campo de senha redondo
    
    # Cores de Status
    check_color = rgb(204, 136, 34)    # Laranja enquanto verifica a senha
    fail_color = rgb(204, 34, 34)     # Vermelho se a senha estiver errada
    fail_text = <i>Senha incorreta! (Tentativa $ATTEMPTS)</i>
    fail_transition = 300             # Milissegundos de transição suave
    
    position = 0, -20
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 64
    font_family = Noto Sans
    position = 0, 80
    halign = center
    valign = center
}
